### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by ghost** [RitobrotoMukherjee/awesome-book-module-2#4]
1. Clean and readable code. :clap: 
2. Good job for using modular javaScript for separation of concern. :fire: 
3. Good job using an HTML template in your js file. :+1: 
4. In line 56 in bookObj.js, you have exported the checkarray function but it was never used, please remove it.
5. Please fill in the Code Reviewers section in the Readme file.

**Comment by RitobrotoMukherjee** [comment]
Thanks, @chahine-mahdhi , Thanks for the feedback and your time. I will fix these in the class refactoring project.
